index:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
contact:
  path: /{_locale}/contact
  controller: App\Controller\DefaultController::contactAction
products:
  path: /{_locale}/products/{categoryId}
  controller: App\Controller\ShopController::index
  defaults:
    categoryId: 1
search:
  path: /{_locale}/search
  controller: App\Controller\ShopController::search
shopping-cart:
  path: /{_locale}/shopping-card
  controller: App\Controller\ShoppingCartController::index
add-to-cart:
  path: /{_locale}/add-to-cart/{productId}
  controller: App\Controller\ShoppingCartController::addToCart
remove-from-cart:
  path: /{_locale}/remove-from-cart/{productId}
  controller: App\Controller\ShoppingCartController::removeFromCart
reset-cart-item:
  path: /{_locale}/reset-cart-item/{productId}
  controller: App\Controller\ShoppingCartController::resetCartItem
reset-cart:
  path: /{_locale}/reset-cart
  controller: App\Controller\ShoppingCartController::resetCart
clear-session:
  path: /{_locale}/clear-session
  controller: App\Controller\DefaultController::clearSession